apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeapp
        env: canary
    spec:
      containers:
        - name: front-end
          image: pavanraj29/nodejs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
