apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: front-end
          image: pavanraj29/nodejs-app-demo
          ports:
            - containerPort: 5000
